# Generated by Django 5.0.2 on 2024-02-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_venta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id',
        ),
        migrations.AddField(
            model_name='venta',
            name='operacion',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
