# Generated by Django 5.0.2 on 2024-02-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_venta_cantidad_alter_venta_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
