# Generated by Django 5.0.2 on 2024-02-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_venta_cantidad_alter_venta_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='precio_unitario',
            field=models.FloatField(),
        ),
    ]
