# Generated by Django 5.0.2 on 2024-02-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_venta_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='precio_neto',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_unitario',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
