# Generated by Django 5.0.2 on 2024-02-11 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_venta_precio_neto_alter_venta_precio_unitario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
        migrations.AlterField(
            model_name='venta',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.FloatField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='operacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_neto',
            field=models.FloatField(default=0, verbose_name='precio neto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_unitario',
            field=models.FloatField(default=0, verbose_name='precio unitario'),
        ),
    ]
