# Generated by Django 5.0.2 on 2024-02-09 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fecha_alta',
            field=models.DateField(editable=False, verbose_name=datetime.datetime(2024, 2, 9, 19, 11, 54, 713270)),
        ),
    ]
