# Generated by Django 5.0.2 on 2024-02-09 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_client_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fecha_alta',
            field=models.DateField(editable=False, verbose_name=datetime.date(2024, 2, 9)),
        ),
    ]
