# Generated by Django 5.0.2 on 2024-02-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_client_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fecha_alta',
            field=models.DateField(editable=False),
        ),
    ]
