# Generated by Django 5.0.2 on 2024-02-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_venta_precio_neto_alter_venta_precio_unitario'),
        ('cliente', '0006_alter_client_fecha_alta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Cliente',
        ),
    ]
